### ISSUE TITLE
ipaas-edit-component-options, can I fetch the options for any component?

### ISSUE THREAD

**Issue by gashcrumb** [fabric8io/django#111]
Or will it only work when I've created a connector project and give me the options for the component that connector configures?

Mostly looking to build up a bit more realistic dummy data for frontend development.  Thanks!

**Comment by gashcrumb** [comment]
@davsclaus FYI just in case :-)

**Comment by davsclaus** [comment]
Yes you need a project first. It can then only edit the options of the chose Camel component for that connector

**Comment by davsclaus** [comment]
Mind that not all Camel components have options on the component level.

On endpoint level however they all have options.
