### ISSUE TITLE
Maven plugin to build connector JAR

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/django#5]
[15:48:20]  <jstrachan> figure a mvn plugin would be handy anyway - to check that its got the valid data we need in the right place and stuff
[15:49:32]  <jstrachan> would be nice if we forced folks to add a mvn dependency to a project to mark it as a connector; which then did all the mvn build stuff; but I think we need a plugin for that - an APT plugin can only generate stuff inside the jar I think; can't force a new artifact to be added AFAIK

**Comment by davsclaus** [comment]
Currently you need to add something alike

```
  <build>
    <finalName>foo</finalName>
    <plugins>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>create-connector</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <classifier>camel-connector</classifier>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

**Comment by davsclaus** [comment]
![screen shot 2016-09-21 at 3 55 15 pm](https://cloud.githubusercontent.com/assets/477100/18713800/de03d536-8013-11e6-8faf-ee6fec3c38cc.png)
![screen shot 2016-09-21 at 3 55 36 pm](https://cloud.githubusercontent.com/assets/477100/18713801/de051ba8-8013-11e6-9c61-d54675674e3d.png)

**Comment by jstrachan** [comment]
nice! :)

**Comment by davsclaus** [comment]
So here you have said the citizen developer should only have 2 options
- resource uri
- loader cache

And then the default values for the connector is in the 2nd screenshot, and for the citizen developer he/she will see
- resource uri = blank (this is required so he/she must type something)
- load cache = false (as its a boolean type, and we chose false)

**Comment by davsclaus** [comment]
The generated json file is

```

{
    "scheme":"velocity",
    "name":"dude",
    "type":"aaa",
    "labels":[
        "foo",
        "bar"
    ],
    "endpointOptions":[
        "resourceUri",
        "loaderCache"
    ],
    "endpointValues":{
        "encoding":"utf-8",
        "loaderCache":"false",
        "propertiesFile":"ipaas.properties"
    }
}
```

**Comment by davsclaus** [comment]
A little more complex is for configuring component level values, we can do that, but they will not be chooseable by the citizen developers as he/she ought to only configure on endpoint level.

**Comment by davsclaus** [comment]
And then for the really complex like CXF JMS SQL we need some extra logic to setup data sources, jms connecion factories, and so on.

**Comment by kcbabo** [comment]
Looks very cool!

Does this mean that every connection will be it's own Maven project?  If so, will we have repo for each of these as well?  Thinking about two cases:
- Expert user creating a connection purely through the iPaaS UI.
- Developer looking to contribute a connection with supplemental code/config.  Maybe they create the connection then clone it to bring down?  Or maybe they just publish the whole thing as a Maven artifact?

**Comment by davsclaus** [comment]
When you invoke the create-connector command it adds our maven plugin which package the project with the classifier camel-connector so we can search them in nexus

```
 <build>
    <finalName>bar</finalName>
    <plugins>
      <plugin>
        <groupId>io.fabric8.django</groupId>
        <artifactId>connector-maven-plugin</artifactId>
        <version>2.3-SNAPSHOT</version>
        <executions>
          <execution>
            <id>connector</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

**Comment by davsclaus** [comment]
@kcbabo the expert user can currently do all from web ui by using the forge commands. Using a real IDE gives him/her more power of course but what you have seen here has 100% been done using only the forge commands.

**Comment by davsclaus** [comment]
Yeah for 3rd party to contribute a custom connector, then he/she needs to build this as a maven project and build and publish that to a maven repo. And then we need some way of configuring fabric8 to index that maven repo also.

Or some tool to upload the JAR from local build to the maven repo/nexus that fabric8 provides OOTB, or something.

**Comment by davsclaus** [comment]
16:59:07]  <jstrachan>  rajdavies davsclaus  here's the docs so far for the simpler REST API https://github.com/fabric8io/fabric8-forge/tree/master/fabric8-forge-core#simple-rest-api-for-forge-commands works on any single page command
[16:59:33]  <jstrachan> the query args with secret stuff is only rrequired for mutable stuff (that, say, changes the pom.xml or whatnot)

**Comment by kcbabo** [comment]
OK, would definitely be interested in seeing both paths I described in the demo next week. :-)  I think we are going to need to connect some dots on second option where a developer contributes a custom component implementation.  Not sure how that is actually published to the Maven repository in iPaaS and registered as an available connector.

**Comment by davsclaus** [comment]
I am about to run for beers this friday, just got a text from a neighbor.

So today I managed to get the tooling to create a connector as 
- Java project
- Java source code as Camel component (extends base class from camel-connector)
- Expert developer can chose options and set default values
- Maven plugin slurps this and create a the JAR as if its a "native" Camel component, with a reduced JSon schema file for this component with only the options enabled for the citizen develoer

This should then allow us to use existing tooling and "fool" them into that the connectors are native Camel components (with muss less options).

The missing pieces is to finish implementing camel-connector component, that then takes it to the finish line, and uses the citizen configured options + default values from expert user, and build that as a "real" Camel endpoint which Camel uses at runtime.

**Comment by kcbabo** [comment]
Nice!

**Comment by davsclaus** [comment]
Early example with a `foo` connector that is based on the timer component. The end user only has 2 options
- timerName
- delay

And they can then use it in a route
https://github.com/fabric8io/django/blob/master/examples/foo-example/src/main/java/io/fabric8/FooRoute.java#L24

We need to improved Camel to support components with no context path, so the uri can be simplified to be

```
foo?timerName=hello&delay=2000
```

Or improve the camel-connector to support context-path, so its more natural

```
foo:hello?delay=2000
```

**Comment by davsclaus** [comment]
In this example: https://github.com/fabric8io/django/tree/master/examples

I am using the foo-connector which is a simplified timer component. It only has 2 options the citizen user can edit: timerName and period.

I just got the existing Camel tooling to be able to use the camel-connector's as if they are regular Camel components and then present their UI accordingly:

![foo-connector](https://cloud.githubusercontent.com/assets/477100/18865970/216382ca-849e-11e6-9eb6-b5a136d7dc8e.png)

And after the edit, if I change the name and the period, the uri is updated accordingly

```
        from("foo:hello2?period=2001")
            .to("log:foo");
```
